# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75c6aadd5852bed1bc35f4e661569c575bc0bd76cc9a7e8773795a97cd87c1df6fb75df7c0fe059735cb7a20f99e9bed59a7ab1e2e67634b8695609c0c01148

test:
  secret_key_base: ec014f8421bdbe3b215ccc94da91501303456ccc39cb83d4761ffd379922aba89e37c72494e920d8a9ed833ee27eab533e31a669c1e66bdeb5048236eda73cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
